
# <center>KodeCamp - Data Science</center>

Author: DSC UG - Machine Learning & Artificial Intelligence Division
- INSTAGRAM : [dsc.ug](https://www.instagram.com/dsc.ug/)
- WEBSITE : [bit.ly/DSCUG-WEB](http://bit.ly/DSCUG-WEB)
- EVENT REGISTRATION : [bit.ly/DSCGUNADARMA](http://bit.ly/DSCGUNADARMA)

<font></font>

<font></font>

# Supervised Learning

Kita akan melakukan klasifikasi jenis bunga iris melalui supervised learning. Pertama, kita akan mengupload file dataset ke google colab.

## Get the Data

Download file **dataset.zip** [disini](https://drive.google.com/file/d/1_9jh9VNVUm8EEiPDDqbIqVlKFZ4uZY6C/view?usp=sharing). Lalu upload ke notebook ini.

Untuk meng-ekstrak file zip, kita akan menggunakan fungsi `ZipFile()` dari library zipfile. Kita akan menyerahkan nama file, dan mode sebagai argumen.

<font size=5><center>ZipFile(<font color=darkgrey>nama file</font>, <font color=darkgrey>mode</font>)</center></font>

mode untuk membuka file adalah: 
- 'r' = read
- 'w' = write
- 'x' = execute


In [ ]:
from zipfile import ZipFile

zip = ZipFile('dataset.zip','r')
zip.extractall()
zip.close()

Isi dari file week2.zip adalah:
- Iris.csv
- Mall_Customers.csv
- image1.jpeg

Kita akan melakukan klasifikasi dataset bunga iris yang disimpan dalam file **Iris.csv**.


## Load Data


Untuk menangani data tabel, kita akan menggunakan library Pandas. Pandas mempunyai fungsi `read_csv()` untuk men-load file dengan tipe *csv*.


<font size=5><center>read_csv(<font color=darkgrey>nama file</font>)</center></font>

In [ ]:
import pandas as pd

credit = pd.read_csv('credit_approval.csv')

In [ ]:
credit.head()

Gender    Age   Debt Married  ... Citizen ZipCode Income  ApprovalStatus
0      b  30.83  0.000       u  ...       g   202.0      0               +
1      a  58.67  4.460       u  ...       g    43.0    560               +
2      a  24.50  0.500       u  ...       g   280.0    824               +
3      b  27.83  1.540       u  ...       g   100.0      3               +
4      b  20.17  5.625       u  ...       s   120.0      0               +

[5 rows x 16 columns]

In [ ]:
len(credit)

690

## Data Preparation

Ketika file *csv* di-load dengan Pandas, file tersebut ditangani sebagai <u>DataFrame</u>. Kolom dalam DataFrame disebut Series. Dengan memanggil atribut `columns`, kita bisa melihat daftar nama Series dari DataFrame itu.

In [ ]:
credit.columns

Index(['Gender', 'Age', 'Debt', 'Married', 'BankCustomer', 'EducationLevel',
       'Ethnicity', 'YearsEmployed', 'PriorDefault', 'Employed', 'CreditScore',
       'DriversLicense', 'Citizen', 'ZipCode', 'Income', 'ApprovalStatus'],
      dtype='object')

Untuk mendapatkan salah satu Series, kita bisa memanggil nama DataFrame dan menyerahkan nama Series yang diinginkan ke dalam kurung besar.

<font size=5><center>nama_DataFrame[<font color=darkgrey>nama series</font>]</center></font>

In [ ]:
credit['Age']

0      30.83
1      58.67
2      24.50
3      27.83
4      20.17
       ...  
685    21.08
686    22.67
687    25.25
688    17.92
689    35.00
Name: Age, Length: 690, dtype: float64

Bila ingin mendapat lebih dari 1 Series, kita bisa panggil DataFrame seperti berikut.


<font size=5><center>nama_DataFrame[[<font color=darkgrey>daftar nama series</font>]]</center></font>

In [ ]:
credit[['Debt', 'ApprovalStatus']]

Debt ApprovalStatus
0     0.000              +
1     4.460              +
2     0.500              +
3     1.540              +
4     5.625              +
..      ...            ...
685  10.085              -
686   0.750              -
687  13.500              -
688   0.205              -
689   3.375              -

[690 rows x 2 columns]

In [ ]:
credit.head()

Gender    Age   Debt Married  ... Citizen ZipCode Income  ApprovalStatus
0      b  30.83  0.000       u  ...       g   202.0      0               +
1      a  58.67  4.460       u  ...       g    43.0    560               +
2      a  24.50  0.500       u  ...       g   280.0    824               +
3      b  27.83  1.540       u  ...       g   100.0      3               +
4      b  20.17  5.625       u  ...       s   120.0      0               +

[5 rows x 16 columns]

Untuk mendapatkan fitur datanya, Series yang bukan termasuk fitur akan di-drop. kita akan memanggil fungsi `drop()` dan menyerahkan nama-nama Series non-fitur & aksis sebagai argumen.

<font size=5><center>drop([<font color=darkgrey>daftar nama series</font>], axis=<font color=darkgrey>aksis</font>)</center></font>

Untuk aksis, terdapat 2 pilihan (0 dan 1). Berikut adalah pilihan aksis:
- 0 : Baris (Horizontal)
- 1 : Kolom (Vertikal)

Karena kita akan men-drop kolom, kita akan gunakan aksis 1.

In [ ]:
x = credit.drop('ApprovalStatus', axis=1)

In [ ]:
y = credit['ApprovalStatus']

In [ ]:
x.head()

Gender    Age   Debt Married  ... DriversLicense Citizen ZipCode  Income
0      b  30.83  0.000       u  ...              f       g   202.0       0
1      a  58.67  4.460       u  ...              f       g    43.0     560
2      a  24.50  0.500       u  ...              f       g   280.0     824
3      b  27.83  1.540       u  ...              t       g   100.0       3
4      b  20.17  5.625       u  ...              f       s   120.0       0

[5 rows x 15 columns]

In [ ]:
y.head()

0    +
1    +
2    +
3    +
4    +
Name: ApprovalStatus, dtype: object

In [ ]:
y.unique()

array(['+', '-'], dtype=object)

## Data Splitting

Performa sebuah model hanya bisa diuji terhadap data yang belum pernah dilihat sebelumnya (yang tidak dipakai untuk training). Maka, sebagian dataset harus dipisah sebagai test data. 

Kita memanggil fungsi `train_test_split()` dan menyerahkan dataset dan rasio test data sebagai argumen. Kita akan mengalokasikan 30% dari dataset sebagai test data. 

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
x_train.head()

Gender    Age    Debt Married  ... DriversLicense Citizen ZipCode  Income
279      b  16.25   0.835       u  ...              f       s   200.0       0
684      b  40.58   3.290       u  ...              t       s   400.0       0
413      b  40.58   1.500       u  ...              f       s   300.0       0
493      a  20.50  11.835       u  ...              f       g   340.0       0
409      b  17.08   0.250       u  ...              f       g   160.0       8

[5 rows x 15 columns]

## Handling Missing Data

### Numeric Data

In [ ]:
import numpy as np
np.set_printoptions(suppress=True)

num = x_train.select_dtypes(include=np.number)
num.head()

Age    Debt  YearsEmployed  CreditScore  ZipCode  Income
279  16.25   0.835          0.085            0    200.0       0
684  40.58   3.290          3.500            0    400.0       0
413  40.58   1.500          0.000            0    300.0       0
493  20.50  11.835          6.000            0    340.0       0
409  17.08   0.250          0.335            4    160.0       8

In [ ]:
num.isna().sum()

Age              11
Debt              0
YearsEmployed     0
CreditScore       0
ZipCode           6
Income            0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

num_imputer = SimpleImputer(strategy='mean')
num = num_imputer.fit_transform(num)
num

array([[ 16.25 ,   0.835,   0.085,   0.   , 200.   ,   0.   ],
       [ 40.58 ,   3.29 ,   3.5  ,   0.   , 400.   ,   0.   ],
       [ 40.58 ,   1.5  ,   0.   ,   0.   , 300.   ,   0.   ],
       ...,
       [ 23.17 ,  11.125,   0.46 ,   1.   , 100.   ,   0.   ],
       [ 21.08 ,   4.125,   0.04 ,   0.   , 140.   , 100.   ],
       [ 20.   ,   0.   ,   0.5  ,   0.   , 144.   ,   0.   ]])

### Categorical Data

In [ ]:
cat = x_train.select_dtypes(exclude=np.number)
cat.head()

Gender Married BankCustomer  ... Employed DriversLicense Citizen
279      b       u            g  ...        f              f       s
684      b       u            g  ...        f              t       s
413      b       u            g  ...        f              f       s
493      a       u            g  ...        f              f       g
409      b       u            g  ...        t              f       g

[5 rows x 9 columns]

In [ ]:
cat_imputer = SimpleImputer(strategy='most_frequent')
cat = cat_imputer.fit_transform(cat)

In [ ]:
cat

array([['b', 'u', 'g', ..., 'f', 'f', 's'],
       ['b', 'u', 'g', ..., 'f', 't', 's'],
       ['b', 'u', 'g', ..., 'f', 'f', 's'],
       ...,
       ['b', 'u', 'g', ..., 't', 'f', 'g'],
       ['b', 'y', 'p', ..., 'f', 'f', 'g'],
       ['b', 'u', 'g', ..., 'f', 'f', 'g']], dtype=object)

## Data Preprocessing

### Numeric Data

In [ ]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
scaler.fit(num)
num_scaled = scaler.transform(num)

In [ ]:
num_scaled

array([[0.08098242, 0.00416125, 0.0004236 , 0.        , 0.99670675,
        0.        ],
       [0.10092473, 0.00818241, 0.0087047 , 0.        , 0.99482233,
        0.        ],
       [0.13404426, 0.00495481, 0.        , 0.        , 0.99096296,
        0.        ],
       ...,
       [0.22439348, 0.1077418 , 0.00445494, 0.00968466, 0.96846561,
        0.        ],
       [0.12158112, 0.02379137, 0.0002307 , 0.        , 0.80746471,
        0.57676051],
       [0.13756756, 0.        , 0.00343919, 0.        , 0.99048642,
        0.        ]])

### Categorical Data

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
cat_enc = encoder.fit_transform(cat)

In [ ]:
cat_enc

array([[0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]])

### Concatenate All Data

In [ ]:
x_train_prepared = np.concatenate([num_scaled, cat_enc], axis=1)
x_train_prepared

array([[0.08098242, 0.00416125, 0.0004236 , ..., 0.        , 0.        ,
        1.        ],
       [0.10092473, 0.00818241, 0.0087047 , ..., 0.        , 0.        ,
        1.        ],
       [0.13404426, 0.00495481, 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.22439348, 0.1077418 , 0.00445494, ..., 1.        , 0.        ,
        0.        ],
       [0.12158112, 0.02379137, 0.0002307 , ..., 1.        , 0.        ,
        0.        ],
       [0.13756756, 0.        , 0.00343919, ..., 1.        , 0.        ,
        0.        ]])

## Build & Train Model

Data telah siap untuk training model, dan juga sudah di split menjadi train data & test data. Kini saatnya kita menyerahkan data training untuk dipelajari model. Model yang digunakan adalah Support Vector Machine. 

Setalah membuat model, kita memanggil fungsi `fit()` dan menyerahkan data serta label sebagai argumen.

<font size=5><center>fit(<font color=darkgrey>data</font>, <font color=darkgrey>label</font>)</center></font>

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train_prepared, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Setelahnya, kita menguji akurasi model.

In [ ]:
model.score(x_train_prepared, y_train)

0.8902691511387164